name: Publish To NuGet Feeds
description: "A composite action to publish .NET packages to NuGet feeds."
inputs:
  NUGET_API_KEY:
    description: "The NuGet API key for publishing packages"
    required: true
  GITHUB_TOKEN:
    description: "The GitHub PAT token passed from the parent workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: Release
      id: release
      uses: googleapis/release-please-action@v4
      with:
        manifest-file: ".config/.release-please-manifest.json"
        config-file: ".config/release-please-config.json"

    - name: Re-pack with Version
      if: steps.release.outputs.releases_created == 'true'
      id: repack
      shell: bash
      run: task ci:pack

    - name: Publish
      if: steps.release.outputs.releases_created == 'true'
      shell: bash
      run: |
        task ci:publish NUGET_API_KEY=${{ inputs.NUGET_API_KEY }} GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }}
