name: Build, Test & Pack
description: "A composite action to set up .NET and run build and test tasks."
inputs:
  dotnet-version:
    description: "The version of .NET to install"
    required: true
    default: "9.0.x"
runs:
  using: "composite"
  steps:
    - name: Format | Resharper
      shell: bash
      run: task fmt:refactor

    - name: Format | Prettier
      shell: bash
      run: task fmt:prettier

    - name: Format | CSharpier
      shell: bash
      run: task fmt:csharp
