name: Build, Test & Pack
description: "A composite action to set up .NET and run build and test tasks."
inputs:
  dotnet-version:
    description: "The version of .NET to install"
    required: true
    default: "9.0.x"
runs:
  using: "composite"
  steps:
    - name: Get all changed markdown files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

    - name: Format (Resharper)
      shell: bash
      run: task fmt:refactor --vars FILES={{ env.CHANGED_FILES }}

    - name: Format (Prettier)
      shell: bash
      env:
        CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: task fmt:prettier --vars FILES={{ env.CHANGED_FILES }}

    - name: Format (CSharpier)
      shell: bash
      run: task fmt:csharp --vars FILES={{ env.CHANGED_FILES }}
