name: Ensure Conventional Pull Request Titles

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  conventional-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  label:
    name: Add label for PR title validation
    runs-on: ubuntu-latest
    steps:
      - name: Add label
        uses: actions/labeler@v5
