env:
  HUSKY: 0

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "🧪 Build & Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Build, Test and Pack
        uses: ./.github/actions/build-test-pack

      - name: Publish
        uses: ./.github/actions/publish
        with:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
