env:
  HUSKY: 0

on:
  push:
    branches-ignore:
      - main

jobs:
  format:
    name: "🧪 Format"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Format
        uses: ./.github/actions/auto-format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: auto-format"
